Страница блюда + подвал
cofeGB/cofeGB pull request #50
Opened 2021-12-15 18:29 UTC by PankratovaE

2021-12-15 19:22 UTC, cofeGB reviewed
Так мы же подвал делаем 1 на все страницы😁

2021-12-15 19:36 UTC, PankratovaE commented
Да, давайте это все смержим, а потом Валера все это доработает и подвал в итоге будет общим. Мы вроде так договаривались)

2021-12-15 20:12 UTC, pashkoveval requested changes
Заливаем=)

2021-12-16 04:24 UTC, pashkoveval approved these changes

2021-12-16 05:29 UTC, merged